# Usa la imagen base de MySQL
FROM mysql:latest

# Establece las variables de entorno necesarias para inicializar la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=cotizadorbdd1
ENV MYSQL_DATABASE2=cotizadorbdd2


# Exponer el puerto 3306
EXPOSE 3306